[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- FACTORY MEMORY SETTINGS ---
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB

lib_ldf_mode = deep

lib_deps = 
	lvgl/lvgl@^9.2.0
	bodmer/TFT_eSPI@^2.5.0

build_flags = 
	; --- S3 USB, PSRAM & DEBUG ---
	-D BOARD_HAS_PSRAM          ; <--- DAS IST DER LEBENSRETTENDE FIX AUS DEM WERKS-CODE!
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D CORE_DEBUG_LEVEL=3

	; --- LVGL CONFIG ---
	-D LV_CONF_INCLUDE_SIMPLE=1
	-I src
	-D LV_USE_STDLIB_MALLOC=LV_STDLIB_CLIB
	-D LV_USE_STDLIB_STRING=LV_STDLIB_CLIB
	-D LV_USE_STDLIB_SPRINTF=LV_STDLIB_CLIB
	-D LV_FONT_MONTSERRAT_24=1
	-D LV_FONT_MONTSERRAT_28=1
	-D LV_FONT_MONTSERRAT_32=1
	-D LV_FONT_MONTSERRAT_48=1

	; --- TFT_eSPI FIX MIT DEINEN WAVESHARE PINS ---
	-D USER_SETUP_LOADED=1
	-D ST7789_DRIVER=1
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_MOSI=38
	-D TFT_SCLK=39
	-D TFT_CS=45
	-D TFT_DC=42
	-D TFT_RST=-1
	-D TFT_BL=1
	
	; Fonts & Features
	-D LOAD_GLCD=1
	-D LOAD_FONT2=1
	-D SPI_FREQUENCY=80000000